name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.2.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "898d55277b9b4df736dadec335e68684fb8332a12eb31a6b7608a54d4b24ba2c"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
