name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.2.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7c36611f2944ac22bee611fa5f3aa7e21ac5719bd791d5aae506cb03560067b"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
