name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.2.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eccaa56a01104ff334f089bac383e1ceaf5286fa8525bc3cfd55f3349e0e328"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
