name = "Pingspam"
filename = "pingspam-1.2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/wpctvPCF/versions/1.2.0/pingspam-1.2.0.jar"
hash-format = "sha512"
hash = "8f7d189c349a3e60825ac23b5ce504f398fbd019fd6e22ba8bcf25e9ff8cbf9ba8eacfd6a4d3f14192c46c1bdbbb4ccaae40204a3d7e0705e2ce003c029aa9eb"

[update]
[update.modrinth]
mod-id = "wpctvPCF"
version = "Zivj2eod"
